name: Notify Local Server

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://daily-promoted-gar.ngrok-free.app/${{ github.repository }}'
        method: 'POST'